pipeline:
  386:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/386
      repo: codeberg.org/${CI_REPO_OWNER}/minetest-mineclone2-386
      registry: codeberg.org
      tags: latest
      auto_tag: true
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
      build_args: 
        - LANG_ARG=en_US.UTF-8
        - TIMEZONE_ARG=Etc/UTC
        - MINETEST_VERSION_ARG=5.6.1
        - IRRLICHT_VERSION_ARG=1.9.0mt9
        - MINECLONE2_VERSION_ARG=0.81.1
    when:
      event: tag
      branch: main
  amd64:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: codeberg.org/${CI_REPO_OWNER}/minetest-mineclone2-amd64
      registry: codeberg.org
      tags: latest
      auto_tag: true
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
      build_args: 
        - LANG_ARG=en_US.UTF-8
        - TIMEZONE_ARG=Etc/UTC
        - MINETEST_VERSION_ARG=5.6.1
        - IRRLICHT_VERSION_ARG=1.9.0mt9
        - MINECLONE2_VERSION_ARG=0.81.1
    when:
      event: tag
      branch: main
  arm:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/arm/v7
      repo: codeberg.org/${CI_REPO_OWNER}/minetest-mineclone2-arm
      registry: codeberg.org
      tags: latest
      auto_tag: true
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
      build_args: 
        - LANG_ARG=en_US.UTF-8
        - TIMEZONE_ARG=Etc/UTC
        - MINETEST_VERSION_ARG=5.6.1
        - IRRLICHT_VERSION_ARG=1.9.0mt9
        - MINECLONE2_VERSION_ARG=0.81.1
    when:
      event: tag
      branch: main
  arm64:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/arm64/v8
      repo: codeberg.org/${CI_REPO_OWNER}/minetest-mineclone2-arm64
      registry: codeberg.org
      tags: latest
      auto_tag: true
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
      build_args: 
        - LANG_ARG=en_US.UTF-8
        - TIMEZONE_ARG=Etc/UTC
        - MINETEST_VERSION_ARG=5.6.1
        - IRRLICHT_VERSION_ARG=1.9.0mt9
        - MINECLONE2_VERSION_ARG=0.81.1
    when:
      event: tag
      branch: main
  ppc64le:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/ppc64le
      repo: codeberg.org/${CI_REPO_OWNER}/minetest-mineclone2-ppc64le
      registry: codeberg.org
      tags: latest
      auto_tag: true
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
      build_args: 
        - LANG_ARG=en_US.UTF-8
        - TIMEZONE_ARG=Etc/UTC
        - MINETEST_VERSION_ARG=5.6.1
        - IRRLICHT_VERSION_ARG=1.9.0mt9
        - MINECLONE2_VERSION_ARG=0.81.1
    when:
      event: tag
      branch: main
